apiVersion: v1
kind: Service
metadata:
  name: {{ include "ortelius-www.name" . }}
spec:
  selector:
    app: {{ include "ortelius-www.name" . }}
    tier: backend
  ports:
    - name: hugo
      protocol: TCP
      port: 80
      targetPort: 80
